repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      # - id: terraform_tflint
      #   args:
      #     - --args=--config=.tflint.hcl
      #     - --args=--chdir=.

  - repo: local
    hooks:
      - id: trivy
        name: Trivy (Terraform Security Scanner)
        description: Run Trivy vulnerability scanner on Terraform files
        entry: bash -c 'trivy fs --config .trivyconfig.yaml .'
        language: system
        pass_filenames: false
        types: [terraform]
        stages: [pre-commit]
